version: "3"
services:
  app:
    # ビルドコンテキスト docker buildを実行する際の現在の作業ディレクトリ
    build: ./infra/php
    # ホスト側の./srcディレクトリをappサービス内のコンテナ内/dataにマウントする
    volumes:
      - ./src:/data
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      TZ: 'Asia/Tokyo'
    restart: always
    ports:
      - 3306:3306
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - mysql_dev:/var/lib/mysql
  testdb:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysqltest
      TZ: 'Asia/Tokyo'
    restart: always
    ports:
      - 3307:3306
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - mysql_test:/var/lib/mysql
volumes:
  mysql_dev:
  mysql_test: